# vim: ft=yaml

# Offense count: 2
RSpec/AnyInstance:
  Exclude:
    - "spec/acfs/runner_spec.rb"

# Offense count: 24
# Configuration parameters: .
# SupportedStyles: have_received, receive
RSpec/MessageSpies:
  EnforcedStyle: receive

# Offense count: 3
RSpec/StubbedMock:
  Exclude:
    - "spec/acfs/global_spec.rb"
    - "spec/acfs/runner_spec.rb"

# Offense count: 2
# Configuration parameters: IgnoreNameless, IgnoreSymbolicNames.
RSpec/VerifiedDoubles:
  Exclude:
    - "spec/acfs/global_spec.rb"
