# vim: ft=yaml

inherit_from: .rubocop_todo.yml
inherit_gem:
  rubocop-config: default.yml

AllCops:
  TargetRubyVersion: "3.1"
  SuggestExtensions: False

Metrics/BlockLength:
  Exclude:
    - "**/*.gemspec"
    - "spec/**/*.rb"

Metrics/ModuleLength:
  Enabled: False

Lint/ShadowingOuterLocalVariable:
  Enabled: False

RSpec/MultipleMemoizedHelpers:
  Enabled: False

RSpec/NestedGroups:
  Enabled: False

# False positive since Acfs responses ain't Rails responses
RSpecRails/HaveHttpStatus:
  Enabled: False

# False positive since Acfs responses ain't Rails responses
RSpecRails/HttpStatus:
  Enabled: False
