# vim: ft=yaml

inherit_from: .rubocop_todo.yml
inherit_gem:
  rubocop-config: default.yml

AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: False

Metrics/BlockLength:
  Exclude:
    - "**/*.gemspec"
    - "spec/**/*.rb"

Metrics/ModuleLength:
  Enabled: False

Lint/ShadowingOuterLocalVariable:
  Enabled: False

RSpec/MultipleMemoizedHelpers:
  Enabled: False

RSpec/NestedGroups:
  Enabled: False
