# vim: ft=yaml

name: test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  rspec:
    name: "Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}"
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        ruby: ["4.0", "3.4", "3.3"]
        rails: ["8.1", "8.0", "7.2"]

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: True

      - run: |
          bundle exec rspec --force-color --format documentation

      - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}

  rubocop:
    name: rubocop
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "4.0.5"
          bundler-cache: True
        env:
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3

      - run: bundle exec rubocop --parallel --color
